### ISSUE TITLE
Exiting shouldn't kill PowerShell

### ISSUE THREAD

**Issue by jdhitsolutions** [smitpi/PSLauncher#2]
I understand that using the form blocks the console. But when clicking the `Exit` button on the GUI, I expect the GUI to close and give me the console back. Instead, it is killing my PowerShell session.

**Comment by smitpi** [comment]
With the changes I made regarding logging, I think it's giving the behavior you're looking for now.

When executing it from an interactive session. The window stays open with no prompt, until the Gui is closed, and the prompt returned. 

If launched from a ps1 script, the script closes once you exit the Gui.

Was this what you were looking for?

**Comment by jdhitsolutions** [comment]
If you pushed a new release I will have to try again. I know that when I clicked the button to run a script or command I see a new console window open, run the code, and then close. There's no way to see a result. Unless, of course, that is your model.

**Comment by smitpi** [comment]
In a perfect world where all commands run equally, it would have been by design to hide everything from the user.

But you need to be able to see the commands run to troubleshoot anything. The change was definitely needed.

Sorry, I should have mentioned. I pushed v0.1.19 to the PSGallery last night. 
I also created a release here on GitHub as well.
